### ISSUE TITLE
In 'break': "If (something)" followed by "since we didn't (something)" is confusing

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-review-conditionals#2]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/review-conditionals?module_item_id=396095

### Concern

Semantics of this statement require extra mental processing:
If we left out the break keyword, the switch statement would get to a match at case 15 and continue on through to case 19, setting isTeenager to true. However, since we didn't break after that assignment, the code would continue...

That is, the first sentence says "If (something or other)" and it is followed by "since we didn't (something or other)"
But wait: You said "if", so asserting "we didn't" seems premature. Reading through this logic requires mental processing that seems unnecessary (i.e. is overhead) for teaching the concept.

### Suggested Changes

Maybe something like this would flow better?

If we leave out the break keyword, the switch statement will get to a match at case 15 and continue on through to case 19, setting isTeenager to true. However, if we don't break after that assignment, the code will continue to execute and isTeenager will wind up being reset to false.

**Comment by lizbur10** [comment]
Hi @brigj1 ! Thanks for providing this feedback. The explanation has been edited to clarify. 💙
